export const SET_FILTER = "SET_FILTER";
export const SET_TODOS = "SET_TODOS";
export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const REMOVE_ALL = "REMOVE_ALL";
export const COMPLETE_STATUS = "COMPLETE_STATUS";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
